/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<system_stm32f4xx.h>
#include <stdint.h>
#include<timer.h>
#include<Ucglib.h>
static ucg_t ucg;
int main(void)
{
	SystemCoreClockUpdate(); //cấp clock
	TimerInit();     		 //để khởi tạo chức năng timer

//Khởi tạo LCD
Ucglib4WireSWSPI_begin(&ucg, UCG_FONT_MODE_SOLID);
ucg_ClearScreen(&ucg);

ucg_SetFont(&ucg, ucg_font_helvB12_tf);//lựa chọn font chữ và cỡ chữ
ucg_SetColor(&ucg, 0, 0, 255, 0);//chọn màu chữ là màu xanh
ucg_SetColor(&ucg, 1,0,0,0);		//màu background là màu đen
ucg_SetRotate180(&ucg);				//quay màn hình lại 180 độ
ucg_DrawString(&ucg, 58,128, 0, "N6_Day5");//in dòng chữ ra LCD
/* Loop foverer */
while(1)
{
	processTimerScheduler();
}
}
